site_name: My Docs
repo_url: https://github.com/weifund/weifund-dapp-basic
site_description: Weifund Documentation
theme: readthedocs
extra_css: [extra.css]
pages:
- Introduction: 'index.md'
- Getting Started:
  - Campaigns: 'getting_started/campaigns.md'
  - Contributing to a Campaign: 'getting_started/contributing_to_a_campaign.md'
  - Getting Ether: 'getting_started/getting_ether.md'
  - Exchange Basics: 'getting_started/exchange_basics.md'
  - Payout a Campaign: 'getting_started/payout_campaign.md'
  - Claim Refund: 'getting_started/claim_refund.md'
  - Reporting a Campaign: 'getting_started/reporting_a_campaign.md'
- Advantages:
  - For Projects: 'advantages/for_projects.md'
  - For Contributors: 'advantages/for_contributors.md'
  - For Curators: 'advantages/for_curators.md'
- Specifications:
  - Overview: 'specifications/overview.md'
  - Campaign Interface Contract: 'specifications/campaign_interface_contract.md'
  - Weifund Contract Interface v1: 'specifications/weifund_contract_interface_v1.md'
  - Properties: 'specifications/properties.md'
  - Campaign Data Specifications: 'specifications/campaign_data_specifications.md'
- Contributing:
  - Contributing: 'contributing/contributing.md'
